# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:
  - name: TNPSC
    url: /
  - name: TET
    url: /
  - name: TNPSC Group IV
    url: /
  - name: VAO
    url: /

# navigation menu
menu:
  - name: Home
    slug: home
    url: /
  - name: Courses
    slug: courses
    url: /Courses
  - name: ContactUs
    slug: contactus
    url: /Contactus
  - name: About
    slug: about
    url: /About

# widgets
widgets:
  - about
  - links
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/ssanjeevi
- slug: twitter
  url: https://twitter.com
- slug: rss
	url: /atom.xml
